[build]
target = "x86_64-unknown-none"

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-none]
rustflags = [
    # Use static relocation model for bare-metal
    "-C",
    "relocation-model=static",

    # Disable position-independent executables
    "-C",
    "code-model=small",

    # Prefer static linking
    "-C",
    "prefer-dynamic=no",

    # Pass linker script
    "-C",
    "link-arg=-T",
    "-C",
    "link-arg=linker.ld",

    # Additional flags for bare metal
    "-C",
    "force-frame-pointers=yes",
]
